"""init

Revision ID: db62e44abb45
Revises: 
Create Date: 2025-04-01 14:34:14.891700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db62e44abb45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dhwalist',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('writer', sa.String(length=150), nullable=False),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.Column('publi', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('list_id', name=op.f('pk_dhwalist'))
    )
    op.create_table('dhwauser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('tell', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dhwauser')),
    sa.UniqueConstraint('email', name=op.f('uq_dhwauser_email')),
    sa.UniqueConstraint('username', name=op.f('uq_dhwauser_username'))
    )
    op.create_table('dhwacart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('writer', sa.String(length=150), nullable=True),
    sa.Column('publi', sa.String(length=150), nullable=True),
    sa.Column('rent_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['dhwalist.list_id'], name=op.f('fk_dhwacart_list_id_dhwalist')),
    sa.ForeignKeyConstraint(['username'], ['dhwauser.id'], name=op.f('fk_dhwacart_username_dhwauser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dhwacart'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dhwacart')
    op.drop_table('dhwauser')
    op.drop_table('dhwalist')
    # ### end Alembic commands ###
